var lang = new Array();
/*弹出框*/
lang['ok']='确定';
lang['cancel']='取消';
lang['tip']='提示';
lang['warning']='警告';
lang['delete_confirm']='删除后不能恢复，确定要删除吗？';
lang['restore_confirm']='恢复数据库将会先删除数据库中全部数据，确定要恢复吗？';
lang['no_rows_selected']='没有选中任何行';
lang['copy_to_clipboard_success']='成功复制到剪贴板';
lang['clear_cache_confirm']='确定要清理缓存吗？缓存清理后将根据系统需要自动重建。';
lang['choose_emotion']='选择表情';
/*微信菜单*/
lang['wechat_menu_title']='标题';
lang['wechat_menu_name']='菜单名称';
lang['wechat_menu_sub_name']='子菜单名称';
lang['wechat_menu_title_null']='没有设置标题';
lang['wechat_menu_null']='没有设置菜单';
lang['wechat_menu_at']='第';
lang['wechat_menu_level1_title_null']='个一级菜单未设置菜单名称';
lang['wechat_menu_level1_at']='个一级菜单中的第';
lang['wechat_menu_level2_title_null']='个二级菜单未设置菜单名称';
lang['wechat_menu']='菜单';
lang['wechat_menu_sub']='子菜单';
lang['wechat_menu_action_null']='未设置操作选项';
lang['wechat_menu_sub_null_and_action_null']='不存在子菜单并且未设置操作选项';
lang['wechat_menu_delete_confirm']='删除一级菜单将同时删除所有子菜单,是否继续';